### ISSUE TITLE
UI Inklusive Mechanismus zur Lokalisation erstellen und kompilieren.

### ISSUE THREAD

**Issue by Inrakie** [fowado/BauphysikSE1#10]
Versuchen einen Standalone Clickdummy in Python zu erstellen.
DIe Lokalisation soll erst einmal in deutsch Erfolgen, doch die möglichkeit die Sprache zu ändern soll einfach gestaltet werden.

**Comment by fowado** [comment]
Clickdummy ist als exe unter Windows10 ausführbar. Issue Closed?

**Comment by salzg** [comment]
UI Oberfläche steht, Verbindung einzelner Elemente zu Gruppen,die auch wieder neu hingezugefügt werden können (z.B. neue Schicht) in Arbeit

**Comment by salzg** [comment]
Schichten in eigenen Widget ausgelagert, momentane Arbeit an Möglichkeit mehrere Widgets der ScrollArea beizufügen

**Comment by salzg** [comment]
habe mich jetzt vom QtDesigner abgewandt, weil er mir nicht die Möglichkeit gegeben hat Dinge anzustellen, die ich für nötig empfand. Keine Sorge, wir verwenden weiterhin PyQt, nur hab ich's diesmal einfach alles manuell geschrieben.

Implentiert wurde:
- Eine MenuBar mit Shortcuts (aktuell nur Dummy)
- Eine Tabansicht
- Modulare Umgebungsbedingungen (momentan nur Widget für Temperatur, aber andere jetzt sehr einfach zu implentieren)
- Modulare Schichten (man kann Schichten einfach hinzufügen und entfernen)
- Placeholder für Visualisierung
- (vermutl.) einfacher Ansatzpunkt für Lokalisierung per QtTranslator (bin mir da nicht so ganz sicher, aber die entsprechenden Konventionen dafür sollte ich befolgt haben)

in naher Zukunft umgesetzt:
- ein "neuer Tab" Button in der Tableiste
- R_ges - Widget (Umgebungsbedingungen/Ergebnisse)
- Button (mal schauen wo) zum Umschalten zwischen den gewünschten Rechnungen

"entfernte Zukunft"/Sachen die ich dafür brauche
- Handling der Menü-Buttons neu, speichern, öffnen, speichern unter: Antwort auf die Frage, wie alles gespeichert werden soll (tabweise oder sessionweise), So kann ich evtl. schon entsprechende Datenstrukturen (intern) anlegen
- Designkritik: Ich bin mit dem Design nicht so ganz zufrieden. Vor allem das GridLayout bei den Layern sieht etwas blöd aus. Ideen sind gern gesehen.

Dieses Issue hiermit closed? Wenn ja, dann lager ich dann meine Wehwehchen in andere Issues aus.
