### ISSUE TITLE
Test proto2

### ISSUE THREAD

**Issue by salzg** [fowado/BauphysikSE1#12]
Bitte ein Mal den Protype testen (proto2/ProtoApril)
.exe befindet sich in /dist.

Es sollte alles (ui-mäßig) funktionieren **ausser** die folgenden Features:
* Menüreiter (nur Dummies)
  * Datei
  * Sprache

* Core Funktionalität
  * Die Berechnung an sich ist nicht drin
  * Öffnen/Speichern/Laden
  * Drucken
  * Visualisierung (ist ein Placeholder)

**Besonders zu beachten:**
Es scheint eine Fehlermeldung per Konsole bei der Benutzung eines AMD-Prozessors zu geben. Da ich nur Intel-CPUs rumfliegen hab, kann ich dem nicht selbst genauer auf den Grund gehen.

**Comment by ChristianLeh** [comment]
Prototyp2 ist getestet. 

Habe bei den vorgenommenen Tests keine Fehler in der Funktionalität gefunden. Für den aktuellen Stand der Software und die damit auf Basis der Anforderungen möglichen Tests gibt es also keine Probleme.

Eine Sache, die ich zur Diskussion spätestens im nächsten Meeting freigeben würde, ist die Funktionalität, die Werte innerhalb der Eingabefelder per Maussrollen zu verändern. 
Habe festgestellt, dass man, wenn man durch mehrere Schichten scrollt, sich dadurch leicht versehehntlich Werte manipuliert, ohne es aktiv zu wollen.
