### ISSUE TITLE
Optik des Prototypen anpassen.

### ISSUE THREAD

**Issue by Inrakie** [fowado/BauphysikSE1#14]
**U-Wertberechnung:**

- lamba rein #24 
- R einer Schicht ist gegeben #24 
- datenstrukturen #21

**Nach Termin mit unserer Kundin:**

- spezifische Wünsche unserer Kundin umsetzen.

**Wenn alles erledigt ist und noch Zeit vorhanden:**

- Überarbeitung der Temperaturverlaufsberechnung. #25

**Comment by salzg** [comment]
care to elaborate?

**Comment by salzg** [comment]
Desweiteren (aus Antwort zu #12 abgeleitet)

- Wertveränderung durch Scrollen unterbinden
