### ISSUE TITLE
Use-Case Systemstart

### ISSUE THREAD

**Issue by ChristianLeh** [fowado/BauphysikSE1#15]
Wie in der Teambesprechung vom 27.04.2020 angerissen hier ein Issue zu einem neuen Use-Case.

Dieser Use-Case soll den Programmstart und alles, was man damit verknüpfen kann, beinhalten:

z.B. Anforderungen wie:
- Start der Software ohne Installation
- Betrieb unter Windows 10
- offline / online
- handelsüblicher Rechner, ...

Falls jemandem noch mehr einfällt, gern dazu schreiben.

**Comment by s78950** [comment]
Use-Case wurde erstellt, bisher noch nicht wirklich umfangreich. Kann  ja aber im Laufe des Projektes noch erweitert / angepasst werden. Falls Fehler drin sind, kann man diese gerne korrigieren oder mich darauf aufmerksam machen, dass selbige trifft bei Ergänzungen zu.

**Comment by fowado** [comment]
Wir haben in unserem UC auch beschrieben das die Software mit handelsüblicher Maus/Tastatur bedient wird.
