### ISSUE TITLE
Kundengespräch Fragensammlung

### ISSUE THREAD

**Issue by fowado** [fowado/BauphysikSE1#16]
Im laufe der Nächsten Woche soll das Gespräch über Discord abgehalten werden.
Ich werde mit der Frau Krawietz die Einrichtung durchgehen und sollten wir auf eine Andere Platform wechseln müssen, gebe ich euch Bescheid.

Diese Issue dient zum Sammeln der Offenen Fragen 

Liste der Fragen:

* Soll eine Fehleingabe durch ein Popup oder ähnliche visuelle Signale signalisiert werden?

* Sollen einzelne Tabs und Berechnungen gespeichert werden? Wenn ja in welcher Form (Damit ist nicht die Druckmöglichkeit gemeint)

* Wir hätten gerne mehr Aufgaben und Beispiele damit die Tests einen größeren Scope bekommen.

**Comment by fowado** [comment]
-In welcher Form sollen die Aufgaben und Berechnungen gedruckt werden? Die Auswahl der zu druckenden Elemente ist nach UC variabel aber die Anordnung und das Format ist noch zu klären.

**Comment by salzg** [comment]
bzgl Speichern: Wenn gespeichert werden soll: Alle Tabs in einem oder Tabs einzeln?
Tabs = Berechnungen

**Comment by salzg** [comment]
closed?
