### ISSUE TITLE
Datenstruktur erstellen

### ISSUE THREAD

**Issue by Inrakie** [fowado/BauphysikSE1#21]
Wie im Meeting besprochen eine Kompatible Datenstruktur, die zwischen UI und Funktionskörper genutzt werden kann, erstellen.

**Comment by Mupfelen** [comment]
commit 3f395c84712c1bef8d25bf35a393ef92eabac014 :
Layer-datenstrukturen und Calculation

**Comment by Mupfelen** [comment]
commit 0bfc3f6a76d847d05661204d282226137d68ba9f
Gemäß gespräch erstellte Datenstruktur+berechnungen
