### ISSUE TITLE
U-berechnung

### ISSUE THREAD

**Issue by Inrakie** [fowado/BauphysikSE1#22]
Rudimentäre funktionalität gewährleisten.
Einfache Berechnung von U. 
Alle Erforderlichen Werte sind vorhanden (Lambda und R).

**Comment by fowado** [comment]
ZIEL: Ende der Woche sind die ersten Berechnungen möglich.

**Comment by Mupfelen** [comment]
commit 0bfc3f6a76d847d05661204d282226137d68ba9f
Berechnungen U und Temperaturen für naive Fälle

**Comment by Mupfelen** [comment]
Testen der Berechnungen benötigt @ChristianLeh
