### ISSUE TITLE
Negative Werte in Zahlenfeldern

### ISSUE THREAD

**Issue by salzg** [fowado/BauphysikSE1#29]
momentan keine Möglichkeit z.B. negative Temperaturen einzufügen

**Comment by salzg** [comment]
negative Temperaturen nun bei den Umgebungsbedingungen einfügbar.
Problem ist jedoch, dass die DoubleSpinBox damit größer wurde. Ich bekomms jedoch nicht hin sie wieder regular size zu machen. Irgendwer Ideen?

**Comment by fowado** [comment]
fixed
20 min Arbeit 
hinzugefügt wurde:
setMaximumWidth / setMinimumWidth zu den spinboxen
Note:
Absolute, feste Size festgelegt. Sollten evtl alles einheitlich machen.
