### ISSUE TITLE
Tool für Code Review

### ISSUE THREAD

**Issue by fritzschefelix** [fowado/BauphysikSE1#30]
Im Meeting wurde die Github-Funktion code review als Möglichkeit genannt.
Die Funktion ist eher eine Möglichkeit Code von anderen Personen Prüfen zu lassen, bevor er ins Repository kommt. Also ungeeignet um jedem Teammitglied einen Überblick über den Code zu verschaffen.

--> Deshalb: Discord mit Bildschirmübertragung und Erklärung der devs.

**Comment by fritzschefelix** [comment]
Gearbeitete Zeit: 10 Minuten

**Comment by salzg** [comment]
ok
