### ISSUE TITLE
Logikprogrammierung für Berechnung

### ISSUE THREAD

**Issue by ChristianLeh** [fowado/BauphysikSE1#37]
Es soll ermittelt und festegestellt werden, ob eine Einbindung bzw Programmierung einer Logik wie Prolog in Python möglich ist und damit die Berehnung flexibler und multifunktionaler gemacht werden kann.

**Comment by ChristianLeh** [comment]
Verschiedene Szenarien angesehen und geprüft. Basierend auf eigenen Erfahrungen mit Möglichkeiten beschäftigt, die sich an der Logikprogrammierung von Prolog orientieren. 

Aufschlussreich war die Masterarbeit von Herrn Stefan Bodenlos "Integration von Prolog und
ClioPatria in Python".

In dieser Arbeit, wie auch in den eigenen Recherchen, kristallisierte sich die Erweiterung Pyswip als beste Lösungsvariante  für die logikprogrammierung in Python aus den verschiedenen Möglichkeiten heraus.

Allerdings würde die Nutzung dieser Erweiterung die Installation von Pyswip, sowie von SWI-Prolog erfordern, was der Grundanforderung der installationslosen Nutzbarkeit der Berehnungssoftware widerspricht.

Meine Empfehlung demnach, auf Logikprogrammierung in dem Projekt zu verzichten.

Arbeitszeit: 2 Stunden

**Comment by fowado** [comment]
Finale Entscheidung beim nächsten Meeting durch Yewgenij

**Comment by salzg** [comment]
Nach umfangreichen Versuchen den gewünschten Sachverhalt in logpy bzw. kanren darzustellen, kam ich zum Schluss, dass der Aufwand nicht in einem sinnvollen Verhältnis zum Nutzen stehen würde.
Es müsste bei einer imperativen - aber auch einer deklarativen - Umsetzung eine Fallunterscheidung vorgenommen werden, damit auch die gewünschte Variable ausgerechnet wird.
Darüberhinaus fehlt es beiden Modulen an umfangreicher Dokumentation und Tutorials.

Demzufolge schlage ich vor dieses Lösungsansatz nicht weiter zu verfolgen.

Zeit: 5 Stunden
