### ISSUE TITLE
Zahlendarstellung von 2 Stellen nach Komma zu 3 Stellen nach Komma

### ISSUE THREAD

**Issue by fowado** [fowado/BauphysikSE1#42]
Einige Aufgaben mit explizit 3 Stellen nach dem Komma als Ergebnis

**Comment by fowado** [comment]
Für alle Zahlen?

**Comment by ChristianLeh** [comment]
Also auf jeden Fall für die Wärmeleitfähigkeit (Lambda). 

Für R kann ich mir auch vorstellen, dass diese Genauigkeit generell Sinn macht, also auch für die berechneten Werte.

Für die Dicke gibt es zwar Aufgaben mit gegebenen 0,175 m, aber da wir ja auch cm als Einheit haben könnte das der Nutzer mit 17,5 cm eingeben, falls dies vom Nutzer erwartet werden kann.

**Comment by salzg** [comment]
10'
