### ISSUE TITLE
Test der Temperaturberechnungen

### ISSUE THREAD

**Issue by Mupfelen** [fowado/BauphysikSE1#45]
Für die in commit 0bfc3f6a76d847d05661204d282226137d68ba9f hinzugefügte Temperaturberechnung Tests durchführen @ChristianLeh

**Comment by salzg** [comment]
Jetzt auch auch in GUI testbar

**Comment by ChristianLeh** [comment]
Temperaturberechnung wurde in GUI mit allen Testscripten getestet.

3 von 5 Tests liefen ohne Probleme und lieferten die erwarteten Ergebnisse.

Bei 2 Tests der nahezu gleichen Aufgabe wich die Temperatur zwischen den 2 Schichten erheblich vom erwarteten Wert ab. Dreht man die Werte der Schichten, kam das erwartete Ergebnis heraus.
Könnte meiner Meinung nach an einer fehlerhaften Rechnung in der übermittelten Aufgabe liegen und nicht an Programmfehler. Dies müsste noch erörtert werden.

Dauer: 0,5 h

**Comment by ChristianLeh** [comment]
Auch hier würde ich Issue erst schließen, wenn auch automatisierte Tests die Funktionen getestet haben.

**Comment by ChristianLeh** [comment]
Automatisierte Testabläufe zum Test der Backend-Funktionalität existieren und laufen ohne Fehler durch. Die oben beschriebene Abweichung verschwindet, wenn man die Werte entsprechend anpasst. Damit ist der Punkt erledigt.
