### ISSUE TITLE
Test der u-Berechnung

### ISSUE THREAD

**Issue by Mupfelen** [fowado/BauphysikSE1#46]
Für die in commit 0bfc3f6 hinzugefügte U-Berechnung Tests durchführen @ChristianLeh

**Comment by salzg** [comment]
Jetzt auch auch in GUI testbar

**Comment by ChristianLeh** [comment]
U-Berechnung wurde in GUI mit allen zur Verfügung stehenden Testscripten getestet.

Tests waren erfolgreich und führten zu korrekten Ergebnissen. Einmal gab es eine Abweichung vom erwarteten Wert für U von 0,0001.

Würde es im Team besprechen, wie wir mit der Abweichung umgehen.

Dauer 0,5 Stunden.

**Comment by ChristianLeh** [comment]
Würde Issue schließen, wenn die automatisierten Tests existieren und damit ebenfalls die Berechnunsfunktionen getestet wurden.

**Comment by ChristianLeh** [comment]
Berechnungsfunktionen wurden auch mit automatisieren Tests erfolgreich geprüft. Damit ist Issue abgeschlossen.
