### ISSUE TITLE
DoubleLinkedList für Layer-Liste in Datenstruktur anlegen

### ISSUE THREAD

**Issue by salzg** [fowado/BauphysikSE1#48]
Die LinkedList für das Abspeichern der Layer fehlt. Ohne die, ist die Datenstruktur nicht nutzbar und somit auch keine (sinnvolle) Anbindung an die UI möglich

**Comment by salzg** [comment]
Eine DoubleLinkedList (siehe DLinkedList.py) hab ich euch mal erstellt. Jetzt bitte an die Datenstruktur auch sinnvoll anbinden.
60'

**Comment by salzg** [comment]
Ihr habt das in der Calculation dem Anschein nach mit Arrays gemacht. Diese sind zu unflexibel in Bezug auf Layers hinzufügen (egal an welcher Stelle) und Layers löschen (egal an welcher Stelle). _Zumindest kenn ich das so aus Java, C usw. Vielleicht handelt das Python anders, aber das bezweifle ich mal stark..._
Die angefragten (siehe Dev-Brainstorm) getter und setter fehlen, aber gut, man kann zur Not auch direkt auf den Attributen schreiben...

Ich wiederhole hier ausdrücklich: **Ich kann euch von Seiten des Frontends keine schönen Arrays/Listen direkt liefern.** Die Layers z.B. sind in einem Layout, wo aber auch andere Sachen (Trennlinien usw.) drinliegen. Deswegen brauche ich Datenstrukturen, die ich an den entsprechenden Stellen beschreiben kann und mit denen im Hintergrund dann gerechnet werden kann.
D.h. ich brauch:
- in TabData eine Funktion, mit der ein (neues) LayerData Objekt in die LinkedList an passender Stelle aufgenommen wird
- in TabData eine Funktion, mit der die Liste angepasst werden kann (Fallbeispiel Layer wird gelöscht)
- generell in TabData das ganze Layer-Handling für das Backend (add, move, delete,...) von was man auch im Frontend machen (könnte _Hier mögliche kommende Funktionalitäten beachten_ ).
- in TabData (und evtl. LayerData, entscheidet euch wie es besser passt) das ganze Calculation-Handling. Ich will im FrontEnd nichts weiter von der Calculation als einen einzelnen Funktionscall wissen. Diese Funktion soll dann die Berechnungen direkt oder indirekt durchführen und die Datenstrukturen beschreiben. Dann hole ich mir die Daten für das Frontend aus den Datenstrukturen wieder.
So wie die Datenstruktur momentan ist, kann ich maximal die Umgebungsbedingungen eintragen.

Bei Rückfragen steh ich auch unter Discord zur Verfügung. Innerhalb meiner aktiven Zeit (1200-2400) sollte ich euch spätestens innerhalb einer Stunde geantwortet haben.

30'

**Comment by Inrakie** [comment]
Dev Meeting 1h größtenteils resolved

**Comment by Mupfelen** [comment]
nach meeting resolved mit commit e283f5ef262fe4e76ecd368edb6884faccec64d8
