### ISSUE TITLE
Farbliche Gestaltung der UI nach vorgegebenem Schema durchsetzen.

### ISSUE THREAD

**Issue by Inrakie** [fowado/BauphysikSE1#52]
EIn Beispiel zu dem Schema ist hier zu finden: 
https://github.com/fowado/BauphysikSE1/blob/master/BauphysikColor01.png

Das Logo hier:
https://github.com/fowado/BauphysikSE1/blob/master/BauphysikLogo01.png
https://github.com/fowado/BauphysikSE1/blob/master/BauphysikLogo02.png

**Comment by salzg** [comment]
duplicate of #34 and #41
