### ISSUE TITLE
Temperaturgraph testen 

### ISSUE THREAD

**Issue by salzg** [fowado/BauphysikSE1#56]
Ich habe für den Graphen pyqtgraph verwendet. Dies verträgt sich nicht so gut mit Windows und Python 3.8. Hier mal besonders Acht geben.
Desweiteren kann es sein, dass cross-platform nicht mehr gegeben ist. Da wir gezielt auf Windows absehen, könnte das in unserem Projekt irrelevant sein, aber gesagt haben wollte ich es trotzdem.

**Comment by ChristianLeh** [comment]
Temperaturgraph habe ich in Verbindung mit den Tests zum Temperaturverlauf getestet. Gab keine Probleme und die Grafik war problemlos nutzbar. Habe Python 3.7 auf dem Rechner soweit ich weiß.

In Verbindung mit Aufgaben, bei denen nur der R-Wert der jeweiligen Wandschicht gegeben war, zeigte die Grafik logischerweise nur einen senkrechten Strich. An der Stelle fehlt dann die Schichtdicke für die Darstellung
 Da sollten wir uns eventuell nochmal Gedanken machen, ob wir das an der Stelle anders haben wollen.
