### ISSUE TITLE
Lücke im Protokoll

### ISSUE THREAD

**Issue by salzg** [fowado/BauphysikSE1#6]
Im 2, Kundengespräch fehlt der Inhalt der Frage zu Aktualisierungsschnittstellen und die entsprechende Antwort. Bitte mir diese Infos zukommen lassen, damit sie ins Protokoll aufgenommen werden können bzw. beim nächsten Kundengespräch ein weiteres Mal fragen.

**Comment by s77815** [comment]
Die Fragen waren:
- Muss das Softwaresystem aktualisiert werden können?
- Soll das Softwaresystem um weitere Funktionen erweiterbar sein?

Dabei hat die Kundin etwa folgendes geantwortet:
- Das Softwaresystem muss im Hinblick auf Materialdaten aktualisierbar sein.
- Bei den Berechnungsvorschriften ist von keinen Änderungen auszugehen. Die Funktionen des Softwaresystems müssen deshalb nicht aktualisierbar sein.
- Sofern wir Funktionen zu den Berechnungen mit parallelen Schichten und der Tauwasserfreiheit implementieren, sieht die Kundin keine Erweiterungsmöglichkeiten im Themengebiet des Wärmedurchgangs.

**Comment by salzg** [comment]
fixed
