### ISSUE TITLE
Testen der Dateispeicherung und -auslesung

### ISSUE THREAD

**Issue by Mupfelen** [fowado/BauphysikSE1#60]
Test der in commit 67e6585ce46bca82f4e2e2d7b5c8abc7c541b294 hinzugefügten Exporter.py und Parser.py

**Comment by ChristianLeh** [comment]
Tests wurden im Backend automatisiert durchgeführt. Nach geringfügigen Anpassungen des Codes funktionierten der Export der Daten in eine Datei, sowie der Import in eine Datenstruktur ohne Probleme. Der automatisierte Test befindet sich in der Datei TestScript_33.py.
Damit kann die Anbindung der Funktionalität an das Frontend starten.

Arbeitszeit: 2 Stunden
