### ISSUE TITLE
Anbindung von Import und Export an UI

### ISSUE THREAD

**Issue by ChristianLeh** [fowado/BauphysikSE1#62]
Nach erfolgreichem Test der Export- und Import-Funktionen in Exporter.py und Parser.py kann die Funktionalität an das Frontend eingebunden werden.

**Comment by salzg** [comment]
~ 2h (aktueller Aufwand, schwer zu messen, weil ich parallel Denis beim Drucken geholfen hab) + 1h Vorbereitung (schon mehere commits vorher convinience functions geschrieben)
