### ISSUE TITLE
Druckauftrag Testen

### ISSUE THREAD

**Issue by fowado** [fowado/BauphysikSE1#63]
Druckauftrag ist fertig. 
Bitte testen ob die Daten korrekt angezeigt werden.

Das Aussehen des Dokuments ist noch in Arbeit also noch kein visuelles Feedback.

**Comment by ChristianLeh** [comment]
Druckauftrag erfüllt nach Anpassungen alle Anforderungen und es werden sämtliche Werte, Beschriftungen und der Graph korrekt angezeigt.
