### ISSUE TITLE
Import/Export per UI testen

### ISSUE THREAD

**Issue by salzg** [fowado/BauphysikSE1#64]
#62 wurde umgesetzt.

**Comment by ChristianLeh** [comment]
Export der Daten per UI funktioniert ohne Fehler bei jeglichen Tests.

**Comment by ChristianLeh** [comment]
Der Import per UI funktioniert bei ursprünglich in Meter eingegebenen Daten problemlos. 

Allerdings ist die Schichtdicke 0,00 nach dem Import, wenn Schichtdicken in cm oder Meter abgespeichert wurden. Liegt wahrscheinlich an der direkten Umrechnung in Meter beim Übergang vom Frontend zum Backend.

**Comment by salzg** [comment]
fixed in commit 754fc2919608bd5f3aeac3d28581ce0a91943e19 

2'
