### ISSUE TITLE
Risikoliste überarbeiten+erweitern

### ISSUE THREAD

**Issue by fritzschefelix** [fowado/BauphysikSE1#7]
Bitte die Risikoliste überarbeiten und gegebenenfalls Anpassen.

Die Liste sollte noch auf mindestens 10 Einträge erweitert werden (siehe Vorlesung). Wer also noch Ideen hat kann diese gerne hinzufügen.

**Comment by s77815** [comment]
Ich habe 5 Risiken aus Analystensicht ergänzt. Die Skalierung von IMP, PRB und MAG ist für mich unklar. Ich habe diese Spalten vorerst mit X bezeichnet und bitte um Erklärung oder direkte Ergänzung.
Auch wenn wir jetzt 10 Risiken haben, wäre eine Risikobetrachtung aus den anderen Perspektiven von Vorteil.
